services:
  - type: web
    name: neurosignal-clinical-hub
    env: node
    plan: free
    rootDir: pdd-website
    buildCommand: "cd frontend && npm install && npm run build && cd ../backend/express-server && npm install"
    startCommand: "cd backend/express-server && node index.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: SMTP_USER
        value: neurosignalai1@gmail.com
      - key: SMTP_PASS
        value: aqpi tlvx slnb eaye
      - key: NEXT_PUBLIC_GEMINI_API_KEY
        sync: false
      - key: ENABLE_NEURAL_UPLINK
        value: "false"
      - key: JWT_SECRET
        value: neurosignal_clinical_secret_key_2026
