services:
  - type: web
    name: neurosignal-clinical-hub
    env: node
    plan: free
    # Updated path to the backend directory
    rootDir: pdd-website/backend/express-server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: SMTP_USER
        value: neurosignalai1@gmail.com
      - key: SMTP_PASS
        value: aqpi tlvx slnb eaye
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: JWT_SECRET
        value: neurosignal_clinical_secret_key_2026
